tools:
  bandit:
    enabled: false
  detekt:
    enabled: false
  eslint:
    enabled: false
  ethlint:
    enabled: false
  hadolint:
    enabled: false
  npmAudit:
    enabled: false
  phpmd:
    enabled: false
  pylint:
    enabled: true
  revive:
    enabled: true
  rubocop:
    enabled: false
  scsslint:
    enabled: false
  tfsec:
    enabled: false
  tslint:
    enabled: false
