name: Fenix Checks

on: [push, pull_request]

jobs:
  check_proto:
    name: Check protobuf file versions (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Check out last commit
        uses: actions/checkout@v2
      
      - name: Set up python3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Run version check
        run: |
          cd protobufs/
          python sum.py
      
  build_server:
    name: Build Fenix server (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Check out last commit
        uses: actions/checkout@v2
        
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'

      - name: Build server
        run: go build -v -o fenix-server ./server

  build_client:
    name: Build Fenix client (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Check out last commit
        uses: actions/checkout@v2
        
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'

      - name: Build client
        run: go build -v -o fenix-client ./client

  run_tests:
    name: Run Fenix tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Check out last commit
        uses: actions/checkout@v2

      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
          
      - name: Run tests
        run: go test ./tests
