name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.4
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run revive linter
      uses: morphy2k/revive-action@v1.3.3
      with:
        config: .revive.toml

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test
      
      run: |
        export FENIX_PASS=${{ secrets.FENIX_PASS }}
        go test -v .
